export const Icons = {
    Back: require("../../assets/back.png").default,
    User: require("../../assets/user.png").default,
    Wallet: require("../../assets/wallet.png").default,
    Security: require("../../assets/security.png").default,
    Event: require("../../assets/event.png").default,
    Notification: require("../../assets/notification.png").default,
    Attendence: require("../../assets/attendence.png").default,
    Logout: require("../../assets/logout.png").default,
    Profile: require("../../assets/profile.png").default,
    Info: require("../../assets/info.png").default,
    Calendar: require("../../assets/calendar.png").default,
    Clock: require("../../assets/clock.png").default,
    Group: require("../../assets/group.png").default,
    logo: require("../../assets/Blacklogo.svg").default,
}